Add onSelectionEnd function parameter to CircularSlider
davidanaya/flutter-circular-slider pull request #5
Opened 2019-05-12 01:36 UTC by kirkeaton

This pull request adds an additional callback function for when the slider selection has ended. This may be useful in cases where the value of the slider maybe be used to update a value on a server or database. In these cases one could use this function as opposed to onSelectionChange to avoid updating too often.

2019-06-09 15:50 UTC, davidanaya commented
@kirkeaton thanks for your PR
Sorry I was not aware of it before and I did a few extra updates in the last days.
Could you please review it and fix the conflicts? Otherwise I will incorporate your suggestion myself when I have some time.

2019-06-09 21:17 UTC, kirkeaton commented
@davidanaya 
I have just rebased this PR against the latest code base, fixed all of the conflicts, and added my changes to the SingleCircularSlider as well.

2019-06-10 08:14 UTC, davidanaya commented on lib/src/circular_slider_paint.dart
> +  final Function onSelectionEnd;
we could use the same typedef that I created for `onSelectionChange` (see line above)

2019-06-10 08:14 UTC, davidanaya commented on lib/src/circular_slider_paint.dart
> +  final Function onSelectionEnd;
please note that we should also return the laps now

2019-06-10 08:15 UTC, davidanaya commented on lib/src/circular_slider_paint.dart
> +    }
this is a bit more complex now
we could have both handlers selected (click on the selection and dragging moves the whole selection) so we would need to account for that (check lines 243 to 251 in this same file for reference)
also we would need to return also the laps (same lines)

2019-06-10 08:16 UTC, davidanaya commented on lib/src/double_circular_slider.dart
> +  final Function onSelectionEnd;
please use same type than with `onSelectionChange` above

2019-06-10 08:16 UTC, davidanaya commented on lib/src/single_circular_slider.dart
> +  final Function onSelectionEnd;
please use the same type as `onSelectionChange` above

2019-06-10 08:16 UTC, davidanaya commented on lib/src/double_circular_slider.dart
> +          onSelectionEnd: (newInit, newEnd) {
include laps

2019-06-10 08:17 UTC, davidanaya commented on lib/src/single_circular_slider.dart
> +            if (widget.onSelectionEnd != null) {
include laps

2019-06-10 08:18 UTC, davidanaya requested changes
Thanks, it's looking good but there are a few things that need to be updated to incorporate the latest features in the library.

2019-06-10 22:45 UTC, kirkeaton commented
@davidanaya Thanks for the review. I think I've addressed all the changes. I've consolidated the panning logic into a separate function to reduce duplicated code as well.

2019-06-11 05:25 UTC, davidanaya commented on lib/src/circular_slider_paint.dart
>      if (_isInitHandlerSelected) {
I think this is unreachable unless you remove the previous code (lines 261 to 264)

2019-06-11 05:26 UTC, davidanaya requested changes
Only one thing missing, I think.

2019-06-11 11:37 UTC, kirkeaton commented
@davidanaya Thanks, I went ahead and remove that if statement.

2019-06-12 05:40 UTC, davidanaya approved these changes
LGTM 🚀 
You can go ahead and merge it.
I'll test it tonight and if it works fine I'll do a release.
Thanks!

2019-06-12 10:56 UTC, kirkeaton commented
@davidanaya Thank's for approving! I'm unable to merge as I don't have write access to the repository.

2019-06-12 18:14 UTC, merged